site_name: Brandon Parker
site_url: https://brandonparker.github.io/my-portfolio/

# theme:
#   name: material
#   palette:
#     -scheme: default
#     toggle:
#       icon: material/weather-night
#       name: Switch to dark mode
#     -scheme: slate
#     toggle:
#       icon: material/weather-sunny
#       name: Switch to light mode
#   

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Resume: Brandon-Ps-Resume3.pdf
  - Contact: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
