site_name: Brandon Parker
site_url: https://brandonparker.github.io/my-portfolio/

# theme:
#   name: material
#   features:
#     - navigation.instant
#     - navigation.top
#     - content.code.copy
#     - content.action.edit
#     - search.suggest
#     - search.highlight

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Resume: Brandon-Ps-Resume3.pdf
  - Contact: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
